version: "3.9"
services:
  html_app:
    build: .
    container_name: harry_html_app1
    ports:
      - "80:80"
    volumes:
      - ./harry_html_app_index/index.html:/usr/share/nginx/html/index.html:ro
    restart: always




